// GENERATED by scripts/grade-rig-frames.mjs. 56 frames extracted from
// assets-src/new-rig-silent.mp4 at 10fps, 1280px wide, webp q70, with
// near-identical head frames trimmed (SSIM >= 0.99 against neighbors).
// Frame 000 is the true closed unit; the last frame is the true exploded
// state and matches /rig/rig-exploded-ink.png exactly.
//
// Grade history. The source render ships on a charcoal studio backdrop with a
// radial falloff, which read as a vignette on the bone page (F-0413), plus
// amber connector accents, which are a banned hue site-wide (F-0421). A first
// pass recast that backdrop into the forest family; the founder rejected the
// green outright (2026-09-03). frames-ink/ is the current pass: the backdrop
// is matted off and replaced with the flat ink token, and the rig is composited
// back by luma alone, so it is monochrome on ink with no cast and no falloff.
// Originals stay at frames/frame-*.webp untouched. Regrade with
// `node scripts/grade-rig-frames.mjs`; the script carries the method.

export const FRAME_COUNT = 56;

export const FRAME_WIDTH = 1280;
export const FRAME_HEIGHT = 720;

export function framePath(i: number) {
  return `/rig/frames-ink/frame-${String(i).padStart(3, "0")}.webp`;
}

// The closed webp is a byte-for-byte copy of frame 000, so the poster and
// the canvas's first drawn frame decode to identical pixels. Same deal for
// the exploded webp and the last frame.
export const RIG_STILLS = {
  closed: { webp: "/rig/rig-closed-ink.webp", png: "/rig/rig-closed-ink.png" },
  exploded: { webp: "/rig/rig-exploded-ink.webp", png: "/rig/rig-exploded-ink.png" },
} as const;
