// GENERATED by the rig frame pipeline. 56 frames extracted from
// assets-src/new-rig-silent.mp4 at 10fps, 1280px wide, webp q70, with
// near-identical head frames trimmed (SSIM >= 0.99 against neighbors).
// Frame 000 is the true closed unit; the last frame is the true exploded
// state and matches /rig/rig-exploded.png exactly.

export const FRAME_COUNT = 56;

export const FRAME_WIDTH = 1280;
export const FRAME_HEIGHT = 720;

export function framePath(i: number) {
  return `/rig/frames/frame-${String(i).padStart(3, "0")}.webp`;
}

// The closed webp is a byte-for-byte copy of frame 000, so the poster and
// the canvas's first drawn frame decode to identical pixels. Same deal for
// the exploded webp and the last frame.
export const RIG_STILLS = {
  closed: { webp: "/rig/rig-closed.webp", png: "/rig/rig-closed.png" },
  exploded: { webp: "/rig/rig-exploded.webp", png: "/rig/rig-exploded.png" },
} as const;
